export const DEMO_ORBITS = [
  {
    id: 'faraday',
    name: 'Michael Faraday',
    initials: 'MF',
    era: '1791–1867',
    field: 'Electromagnetic science',
    gravityProfile: {
      mission: 'Translate invisible natural forces — electricity, magnetism, light — into visible phenomena that anyone can understand and verify. Prove that nature is unified, not fragmented.',
      desiredReputation: 'The experimenter who proved the unity of physical forces',
      thinkingPartner: 'Someone who can take intuitive physical observations and formalize them mathematically — to build what I can sense but cannot fully articulate.',
      story: 'Born the son of a blacksmith, self-taught from books in a bookbinder\'s shop. I found my way to the Royal Institution through sheer obsession with how the world actually works. I want thinking partners who care more about what\'s true than what\'s already known.',
    },
    contacts: [
      { id: 'mf-1', name: 'James Clerk Maxwell', role: 'Mathematician and physicist', status: 'CONVERSATION', why: 'Mathematician and physicist. Translated Faraday\'s field intuitions into precise mathematical equations — giving electromagnetic theory the language it needed to survive.' },
      { id: 'mf-2', name: 'Humphry Davy', role: 'Chemist and Royal Institution director', status: 'CONVERSATION', why: 'Chemist and Royal Institution director. Recognized a bookbinder\'s apprentice as a scientific mind and gave him access to the laboratory that changed everything.' },
      { id: 'mf-3', name: 'William Whewell', role: 'Philosopher of science', status: 'IDENTIFIED', why: 'Philosopher of science. Coined the terms ion, electrode, and cathode to name what Faraday was observing — proof that naming a thing is part of discovering it.' },
      { id: 'mf-4', name: 'Charles Babbage', role: 'Mathematician and inventor', status: 'REPLIED', why: 'Mathematician and inventor. Working to make logic mechanical at the exact moment Faraday was making electricity legible. Two people trying to impose rules on invisible forces.' },
      { id: 'mf-5', name: 'John Tyndall', role: 'Physicist and science communicator', status: 'REPLIED', why: 'Physicist and science communicator. Championed Faraday\'s work to the public and continued his research at the Royal Institution after him.' },
    ],
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    initials: 'NT',
    era: '1856–1943',
    field: 'Electrical engineering',
    gravityProfile: {
      mission: 'Harness alternating current to deliver unlimited electrical power to every human on earth — and eventually transmit energy through the earth itself without wires.',
      desiredReputation: 'The inventor who rewired civilization',
      thinkingPartner: 'Someone who thinks in systems and understands that the dominant technology is rarely the best one — just the one that found money first.',
      story: 'I can visualize complete machines running in my mind before a single component is built. I need people around me who can hold a vision that does not yet exist in the world and treat it as already real.',
    },
    contacts: [
      { id: 'nt-1', name: 'George Westinghouse', role: 'Industrialist and inventor', status: 'CONVERSATION', why: 'Industrialist and inventor. The only financier who understood AC power as a philosophy, not just a technology — backed the Niagara Falls transmission that proved Tesla right.' },
      { id: 'nt-2', name: 'Thomas Edison', role: 'Inventor and businessman', status: 'IDENTIFIED', why: 'Inventor and businessman. Represents the DC model Tesla is displacing — power as property, science as commerce. Understanding your opposition is part of the work.' },
      { id: 'nt-3', name: 'Mark Twain', role: 'Writer and satirist', status: 'REPLIED', why: 'Writer and satirist. Close friend and regular presence in the lab. Saw Tesla as a fellow outsider to convention and understood the poetry inside the engineering.' },
      { id: 'nt-4', name: 'Swami Vivekananda', role: 'Philosopher and Hindu monk', status: 'REPLIED', why: 'Philosopher and Hindu monk. Described prana and akasha — energy and matter as unified substance — in terms that mapped directly onto Tesla\'s electrical field theories.' },
      { id: 'nt-5', name: 'Ernst Mach', role: 'Physicist and philosopher of science', status: 'IDENTIFIED', why: 'Physicist and philosopher of science. His work on the nature of energy and matter gave Tesla a theoretical framework for thinking beyond conventional electromagnetism.' },
    ],
  },
  {
    id: 'fuller',
    name: 'Buckminster Fuller',
    initials: 'BF',
    era: '1895–1983',
    field: 'Design science',
    gravityProfile: {
      mission: 'Design comprehensive systems that allow all of humanity to live well on Earth\'s finite resources — starting with shelter, and ending nowhere.',
      desiredReputation: 'The comprehensive anticipatory design scientist',
      thinkingPartner: 'Someone who can hold the whole system simultaneously — economics, physics, ecology, and the human — without collapsing into any one discipline.',
      story: 'I was expelled from Harvard twice and considered suicide at 32. What stopped me was the question: what can one individual do that large institutions cannot? I\'ve spent the rest of my life finding out.',
    },
    contacts: [
      { id: 'bf-1', name: 'Isamu Noguchi', role: 'Sculptor and designer', status: 'CONVERSATION', why: 'Sculptor and designer. Collaborated on the Dymaxion car and proved across decades that structural engineering and art are the same act approached from different doors.' },
      { id: 'bf-2', name: 'Marshall McLuhan', role: 'Media theorist', status: 'REPLIED', why: 'Media theorist. Argued that media are environments, not just tools — the same insight Fuller held about geometry and architecture. The container shapes the contained.' },
      { id: 'bf-3', name: 'John Cage', role: 'Composer and artist', status: 'REPLIED', why: 'Composer and artist. Proved at Black Mountain College that structure liberates rather than constrains. His 4\'33″ is a design argument disguised as music.' },
      { id: 'bf-4', name: 'Edwin Land', role: 'Inventor and Polaroid founder', status: 'REACHED_OUT', why: 'Inventor and Polaroid founder. Made complex optical science disappear into a single button. The standard Fuller was aiming for — complexity that becomes invisible in use.' },
      { id: 'bf-5', name: 'Jonas Salk', role: 'Virologist', status: 'REPLIED', why: 'Virologist. Cured polio and refused to patent it. Operated from the same premise as Fuller — that the goal is never ownership, it is the solution reaching everyone.' },
    ],
  },
  {
    id: 'dubois',
    name: 'W.E.B. Du Bois',
    initials: 'WD',
    era: '1868–1963',
    field: 'Sociology and civil rights',
    gravityProfile: {
      mission: 'Use the tools of social science — data, history, and narrative — to dismantle the structures that make racial inequality seem natural and inevitable.',
      desiredReputation: 'The scholar-activist who proved that racism is constructed, not innate',
      thinkingPartner: 'Someone who holds both rigorous empirical analysis and moral urgency at the same time — who knows that data alone never changed a mind, but neither did outrage alone.',
      story: 'I am the first African American to earn a doctorate from Harvard. I have written over twenty books. The work does not end.',
    },
    contacts: [
      { id: 'wd-1', name: 'Ida B. Wells', role: 'Journalist and activist', status: 'CONVERSATION', why: 'Journalist and activist. Used documentation as a political weapon before anyone else understood that was possible. Her anti-lynching pamphlets set the standard for evidence as argument.' },
      { id: 'wd-2', name: 'Booker T. Washington', role: 'Educator and leader', status: 'IDENTIFIED', why: 'Educator and leader. Represents the accommodationist position Du Bois spent decades publicly opposing — the argument that must be had to define what the movement actually stands for.' },
      { id: 'wd-3', name: 'Jane Addams', role: 'Social reformer and Hull House founder', status: 'REPLIED', why: 'Social reformer and Hull House founder. Built institutions that made reform structural rather than charitable. Collaborated on early civil rights work across racial lines.' },
      { id: 'wd-4', name: 'Langston Hughes', role: 'Poet and writer', status: 'REPLIED', why: 'Poet and writer. Central voice of the Harlem Renaissance — the cultural infrastructure Du Bois helped create. Art as the nervous system of a political movement.' },
      { id: 'wd-5', name: 'Paul Robeson', role: 'Actor, singer, and activist', status: 'CONVERSATION', why: 'Actor, singer, and activist. Had his passport revoked by the US government for political speech. Solidarity built through shared persecution and the same refusal to be silenced.' },
    ],
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    initials: 'AT',
    era: '1912–1954',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'Define the boundary between what is mechanically computable and what is not — and build the machines that live at that boundary.',
      desiredReputation: 'The mathematician who gave machines the capacity to think',
      thinkingPartner: 'Someone who can think in formal systems without losing sight of the philosophical stakes — who knows that "can machines think" is not just an engineering problem.',
      story: 'I designed the mathematical foundations of computation before there were computers. Then I built them. The question I keep returning to is not whether machines can compute — they can — but whether there is something computation cannot reach.',
    },
    contacts: [
      { id: 'at-1', name: 'Alonzo Church', role: 'Mathematician and logician', status: 'REPLIED', why: 'Mathematician and logician. Arrived at the same computability result independently using lambda calculus. Two people finding the same boundary from different directions confirms it\'s real.' },
      { id: 'at-2', name: 'John von Neumann', role: 'Mathematician and physicist', status: 'CONVERSATION', why: 'Mathematician and physicist. Building the physical architecture that makes universal computation real. Helped create the first working stored-program computer.' },
      { id: 'at-3', name: 'Claude Shannon', role: 'Mathematician and electrical engineer', status: 'CONVERSATION', why: 'Mathematician and electrical engineer. Quantifying information itself — giving it a unit of measure. The missing bridge between computability theory and a physical thinking machine.' },
      { id: 'at-4', name: 'Dilly Knox', role: 'Cryptanalyst and Bletchley Park veteran', status: 'REPLIED', why: 'Cryptanalyst and Bletchley Park veteran. The first person in an institution to recognize Turing\'s abilities and create space for him to work without interference.' },
      { id: 'at-5', name: 'Max Newman', role: 'Mathematician', status: 'REACHED_OUT', why: 'Mathematician. Supervised Turing at Cambridge and later led the computing group at Bletchley. The through-line of his career — the person who saw what he was before anyone else.' },
    ],
  },
  {
    id: 'goodall',
    name: 'Jane Goodall',
    initials: 'JG',
    era: '1934–',
    field: 'Primatology and conservation',
    gravityProfile: {
      mission: 'Prove through patient observation that chimpanzees — and by extension all animals — have complex inner lives, and use that proof to transform how humans treat the natural world.',
      desiredReputation: 'The scientist who changed what it means to be human by watching other animals',
      thinkingPartner: 'Someone who understands that rigorous science and moral commitment are not in tension — that the facts, honestly seen, lead you to action.',
      story: 'I had no formal degree when Louis Leakey sent me to Gombe. He believed lack of academic conditioning was an advantage. I spent years being dismissed. Then the chimpanzees taught me things the textbooks did not know.',
    },
    contacts: [
      { id: 'jg-1', name: 'Louis Leakey', role: 'Paleoanthropologist', status: 'CONVERSATION', why: 'Paleoanthropologist. Sent her to Gombe without a degree because he believed the question mattered more than the credentials. Made the research possible before it was credible.' },
      { id: 'jg-2', name: 'Hugo van Lawick', role: 'Wildlife photographer and filmmaker', status: 'CONVERSATION', why: 'Wildlife photographer and filmmaker. Made the Gombe observations visible to the world. Without the photographs, the science stays in notebooks nobody reads.' },
      { id: 'jg-3', name: 'Dian Fossey', role: 'Primatologist', status: 'REPLIED', why: 'Primatologist. Asking the same question with gorillas that Goodall is asking with chimpanzees — that the boundary between human and primate is a story, not a fact.' },
      { id: 'jg-4', name: 'David Attenborough', role: 'Natural historian and broadcaster', status: 'REPLIED', why: 'Natural historian and broadcaster. Translated field science into mass audiences. The bridge between what happens in the forest and what changes in living rooms.' },
      { id: 'jg-5', name: 'Rachel Carson', role: 'Marine biologist and writer', status: 'IDENTIFIED', why: 'Marine biologist and writer. Silent Spring created the political environment in which conservation science became urgent rather than academic.' },
    ],
  },
  {
    id: 'lovelace',
    name: 'Ada Lovelace',
    initials: 'AL',
    era: '1815–1852',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'See what the Analytical Engine can do that its inventor has not yet imagined — and write that vision down before the world is ready to understand it.',
      desiredReputation: 'The first to see that a calculating machine could operate on symbols beyond number',
      thinkingPartner: 'Someone who can match mathematical precision with imaginative reach — who does not mistake what a machine has done for what it can do.',
      story: 'My mother insisted on mathematics to suppress my father\'s poetic nature. It did not work as intended. I have come to believe that poetic science — imagination disciplined by rigor — is the only kind worth practicing.',
    },
    contacts: [
      { id: 'al-1', name: 'Charles Babbage', role: 'Mathematician and inventor', status: 'CONVERSATION', why: 'Mathematician and inventor. Designing the Analytical Engine — the machine her algorithm needs to exist. Theory without the machine stays theory forever.' },
      { id: 'al-2', name: 'Mary Somerville', role: 'Mathematician and scientist', status: 'CONVERSATION', why: 'Mathematician and scientist. Validated Lovelace\'s abilities at an age when no institution would. The permission that made everything else possible.' },
      { id: 'al-3', name: 'Michael Faraday', role: 'Physicist', status: 'REACHED_OUT', why: 'Physicist. Making invisible forces obey rules at the exact moment Lovelace is trying to make logic obey rules. Same ambition, different substrate.' },
      { id: 'al-4', name: 'Augustus De Morgan', role: 'Mathematician and logician', status: 'REPLIED', why: 'Mathematician and logician. Tutored Lovelace until he acknowledged she had surpassed his instruction — the most useful thing a teacher can admit.' },
      { id: 'al-5', name: 'William King-Noel', role: 'Earl of Lovelace', status: 'IDENTIFIED', why: 'Earl of Lovelace. Provided the financial stability and social cover that allowed her to work in a world that did not believe women could do mathematics.' },
    ],
  },
  {
    id: 'carson',
    name: 'Rachel Carson',
    initials: 'RC',
    era: '1907–1964',
    field: 'Marine biology and ecology',
    gravityProfile: {
      mission: 'Make the invisible world of ecological interconnection visible enough that ordinary people will fight to protect it — starting with the sea, ending with the land.',
      desiredReputation: 'The scientist who started the modern environmental movement by making facts beautiful',
      thinkingPartner: 'Someone who understands that scientific literacy requires more than data — it requires prose that carries the reader into the world the data describes.',
      story: 'I wrote Silent Spring knowing it would be attacked by the chemical industry with everything they had. I published it anyway. I had cancer by then and no time for caution.',
    },
    contacts: [
      { id: 'rc-1', name: 'Dorothy Freeman', role: 'Friend and correspondent', status: 'CONVERSATION', why: 'Friend and correspondent. Read every draft and pushed Carson to let the story carry the science — the editorial relationship that made Silent Spring what it became.' },
      { id: 'rc-2', name: 'E.B. White', role: 'Writer and essayist', status: 'REPLIED', why: 'Writer and essayist. Championed Silent Spring publicly when the chemical industry attacks were heaviest. Understood that prose is not decoration for argument — it is the argument.' },
      { id: 'rc-3', name: 'Clarence Cottam', role: 'Wildlife biologist', status: 'CONVERSATION', why: 'Wildlife biologist. Provided the scientific data underpinning Silent Spring that the chemical industry could not refute. The research backbone of the most attacked book of its decade.' },
      { id: 'rc-4', name: 'Justice William O. Douglas', role: 'Supreme Court Justice and conservationist', status: 'REPLIED', why: 'Supreme Court Justice and conservationist. Argued for nature\'s legal standing — that you cannot protect what the law does not recognize. Carried Carson\'s argument into the courts.' },
      { id: 'rc-5', name: 'Albert Schweitzer', role: 'Physician and philosopher', status: 'REACHED_OUT', why: 'Physician and philosopher. Carson dedicated Silent Spring to him. His reverence for life as an ethical framework gave her work its moral foundation.' },
    ],
  },
  {
    id: 'ibwells',
    name: 'Ida B. Wells',
    initials: 'IB',
    era: '1862–1931',
    field: 'Investigative journalism and civil rights',
    gravityProfile: {
      mission: 'Document racial violence with enough precision that denial becomes impossible — and publish it regardless of the threats made against the person doing the documenting.',
      desiredReputation: 'The journalist who made racial terror undeniable',
      thinkingPartner: 'Someone who understands that truth documented is not the same as truth heard — who knows that reaching the institutions of power requires strategy as much as evidence.',
      story: 'Born into slavery six months before the Emancipation Proclamation. I owned a newspaper by twenty-five. When three of my friends were lynched in Memphis, I went to the site, gathered the evidence, and published the truth. A mob destroyed my press and warned me out of the city at gunpoint. I kept writing.',
    },
    contacts: [
      { id: 'iw-1', name: 'Frederick Douglass', role: 'Abolitionist and statesman', status: 'CONVERSATION', why: 'Abolitionist and statesman. Wrote the preface to her first anti-lynching pamphlet — a direct passing of the torch between the two most important Black truth-tellers of successive generations.' },
      { id: 'iw-2', name: 'W.E.B. Du Bois', role: 'Sociologist and activist', status: 'REPLIED', why: 'Sociologist and activist. Using data the way Wells uses testimony — to make denial structurally impossible. Building the same case from sociology that she builds from journalism.' },
      { id: 'iw-3', name: 'Jane Addams', role: 'Social reformer', status: 'REPLIED', why: 'Social reformer. Built the institutional infrastructure that gave the anti-lynching campaign political reach. Where Wells made the argument, Addams built the machinery.' },
      { id: 'iw-4', name: 'Mary Church Terrell', role: 'Educator and activist', status: 'CONVERSATION', why: 'Educator and activist. Fellow founder of the NAACP. Understood that Black women needed their own institutions rather than waiting for existing ones to include them.' },
      { id: 'iw-5', name: 'T. Thomas Fortune', role: 'Journalist and newspaper editor', status: 'CONVERSATION', why: 'Journalist and newspaper editor. Gave Wells her first platform and co-owned the New York Age where she published her most important investigative work.' },
    ],
  },
  {
    id: 'arendt',
    name: 'Hannah Arendt',
    initials: 'HA',
    era: '1906–1975',
    field: 'Political philosophy',
    gravityProfile: {
      mission: 'Understand how totalitarianism became possible — and in understanding it, identify what political action and public life must protect against it ever happening again.',
      desiredReputation: 'The thinker who refused to let atrocity become incomprehensible',
      thinkingPartner: 'Someone who can think without a banister — who does not need established tradition or ideology to hold their thinking up — who is willing to follow an argument wherever it goes.',
      story: 'I fled Germany in 1933 and was stateless for 18 years. I reported on the Eichmann trial and wrote that evil could be ordinary — banal — and the attacks have not stopped since. I stand by the analysis. Discomfort is not a rebuttal.',
    },
    contacts: [
      { id: 'ha-1', name: 'Mary McCarthy', role: 'Writer and critic', status: 'CONVERSATION', why: 'Writer and critic. Argued with Arendt for forty years without ever letting lazy thinking stand. The rarest kind of intellectual friendship — one that improves both people.' },
      { id: 'ha-2', name: 'Karl Jaspers', role: 'Philosopher', status: 'CONVERSATION', why: 'Philosopher. Maintained correspondence across war, exile, and every border erected between them. Proof that genuine philosophical friendship is more durable than geography.' },
      { id: 'ha-3', name: 'Walter Benjamin', role: 'Philosopher and critic', status: 'REPLIED', why: 'Philosopher and critic. Died at the border Arendt crossed. She carried his manuscripts to safety — understanding that the ideas outlast the person carrying them.' },
      { id: 'ha-4', name: 'Heinrich Blücher', role: 'Philosopher and poet', status: 'CONVERSATION', why: 'Philosopher and poet. Her husband and intellectual partner. The person she thought with most directly — their apartment was the seminar room where her major ideas were tested.' },
      { id: 'ha-5', name: 'Hans Jonas', role: 'Philosopher', status: 'REPLIED', why: 'Philosopher. Fellow student of Heidegger who broke with him over Nazism. Shared Arendt\'s project of salvaging rigorous thinking from a tradition that had compromised itself.' },
    ],
  },
]
