export const DEMO_ORBITS = [
  {
    id: 'faraday',
    name: 'Michael Faraday',
    initials: 'MF',
    era: '1791–1867',
    field: 'Electromagnetic science',
    gravityProfile: {
      mission: 'Translate invisible natural forces — electricity, magnetism, light — into visible phenomena that anyone can understand and verify. Prove that nature is unified, not fragmented.',
      desiredReputation: 'The experimenter who proved the unity of physical forces',
      thinkingPartner: 'Someone who can take intuitive physical observations and formalize them mathematically — to build what I can sense but cannot fully articulate.',
      story: 'Born the son of a blacksmith, self-taught from books in a bookbinder\'s shop. I found my way to the Royal Institution through sheer obsession with how the world actually works. I want thinking partners who care more about what\'s true than what\'s already known.',
    },
    contacts: [
      { id: 'mf-1', name: 'James Clerk Maxwell', role: 'Mathematical physicist', status: 'CONVERSATION', why: 'His equations turned Faraday\'s field intuitions into a unified mathematical language — translating invisible physical sense into the form science needed to transmit it.' },
      { id: 'mf-2', name: 'Humphry Davy', role: 'Chemist, Royal Institution', status: 'CONVERSATION', why: 'His invitation from the Royal Institution handed Faraday the laboratory that became the site of every major discovery — the patron who could recognize signal through class.' },
      { id: 'mf-3', name: 'Charles Wheatstone', role: 'Physicist and inventor', status: 'REPLIED', why: 'His work on electrical telegraphy forced Faraday\'s laboratory insights to prove themselves at distance and scale — the collaborator who turned theory into infrastructure.' },
      { id: 'mf-4', name: 'Joseph Henry', role: 'American physicist', status: 'REACHED_OUT', why: 'His independent discovery of electromagnetic induction — arriving from a different continent by a different method — proved Faraday\'s results were describing something real in nature, not artifact.' },
      { id: 'mf-5', name: 'William Whewell', role: 'Philosopher of science', status: 'IDENTIFIED', why: 'His naming of ion, anode, cathode, and electrolyte gave Faraday\'s observations a language that others could use — the philosopher who understood that science cannot spread without shareable words.' },
      { id: 'mf-6', name: 'John Tyndall', role: 'Physicist, Royal Institution', status: 'REPLIED', why: 'His work on radiant heat and the scattering of light through matter extended Faraday\'s line of inquiry — the colleague at the Royal Institution who carried the experimental tradition forward and defended it publicly.' },
    ],
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    initials: 'NT',
    era: '1856–1943',
    field: 'Electrical engineering',
    gravityProfile: {
      mission: 'Harness alternating current to deliver unlimited electrical power to every human on earth — and eventually transmit energy through the earth itself without wires.',
      desiredReputation: 'The inventor who rewired civilization',
      thinkingPartner: 'Someone who thinks in systems and understands that the dominant technology is rarely the best one — just the one that found money first.',
      story: 'I can visualize complete machines running in my mind before a single component is built. I need people around me who can hold a vision that does not yet exist in the world and treat it as already real.',
    },
    contacts: [
      { id: 'nt-1', name: 'George Westinghouse', role: 'Industrialist and inventor', status: 'CONVERSATION', why: 'His willingness to bet his company on alternating current — when Edison\'s DC monopoly controlled the public narrative — was the only thing that could move Tesla\'s system from laboratory vision to continental grid.' },
      { id: 'nt-2', name: 'Mark Twain', role: 'Author and public intellectual', status: 'REPLIED', why: 'His friendship and public endorsement gave Tesla a form of social legitimacy that patent filings could not supply — proof that unconventional genius can be recognized without being fully understood.' },
      { id: 'nt-3', name: 'Thomas Edison', role: 'Inventor, DC power advocate', status: 'IDENTIFIED', why: 'His campaign against alternating current — including the public electrocution of animals — revealed how entrenched capital fights the technologies that threaten to replace it, a permanent case study in the sociology of technological defeat.' },
      { id: 'nt-4', name: 'J.P. Morgan', role: 'Financier', status: 'REACHED_OUT', why: 'His financing of Wardenclyffe gave Tesla the largest structure of his career, and his withdrawal ended it — the permanent lesson in what happens when visionary technology cannot explain its commercial model.' },
      { id: 'nt-5', name: 'Lord Kelvin', role: 'Physicist', status: 'IDENTIFIED', why: 'His initial opposition to alternating current and subsequent reversal made him the most significant convert — the physicist whose changed mind carried more weight than a dozen favorable experiments.' },
      { id: 'nt-6', name: 'Ernst Mach', role: 'Physicist and philosopher of science', status: 'IDENTIFIED', why: 'His philosophical insistence that scientific theories must be grounded in observable phenomena — and his skepticism of claims that outran experimental proof — provided the critical counterweight to the side of Tesla\'s vision that risked losing science\'s trust.' },
    ],
  },
  {
    id: 'fuller',
    name: 'Buckminster Fuller',
    initials: 'BF',
    era: '1895–1983',
    field: 'Design science',
    gravityProfile: {
      mission: 'Design comprehensive systems that allow all of humanity to live well on Earth\'s finite resources — starting with shelter, and ending nowhere.',
      desiredReputation: 'The comprehensive anticipatory design scientist',
      thinkingPartner: 'Someone who can hold the whole system simultaneously — economics, physics, ecology, and the human — without collapsing into any one discipline.',
      story: 'I was expelled from Harvard twice and considered suicide at 32. What stopped me was the question: what can one individual do that large institutions cannot? I\'ve spent the rest of my life finding out.',
    },
    contacts: [
      { id: 'bf-1', name: 'Kenneth Snelson', role: 'Sculptor and engineer', status: 'CONVERSATION', why: 'His tensegrity sculptures proved that Fuller\'s geometric principles could hold structural integrity in physical space — the artist who demonstrated in steel and wire what the theorist had only described in mathematics.' },
      { id: 'bf-2', name: 'Marshall McLuhan', role: 'Media theorist', status: 'REPLIED', why: 'His argument that every medium reshapes the consciousness of its users extended Fuller\'s insight that structure determines outcome — two thinkers who approached the same problem from opposite disciplines and reached the same conclusion.' },
      { id: 'bf-3', name: 'John Cage', role: 'Composer and philosopher', status: 'REPLIED', why: 'His compositional system — treating silence, noise, and duration as structural elements rather than accidents — showed that radical formal thinking could produce coherence rather than chaos, and that discipline was not the enemy of freedom.' },
      { id: 'bf-4', name: 'Edwin Land', role: 'Inventor and scientist', status: 'REACHED_OUT', why: 'His development of the Polaroid camera proved that a single inventor committed to comprehensive design thinking could bring a genuinely new system to mass production without surrendering the original vision to cost or committee.' },
      { id: 'bf-5', name: 'Stewart Brand', role: 'Futurist and author', status: 'CONVERSATION', why: 'His Whole Earth Catalog carried Fuller\'s systems thinking into the counterculture generation — translating comprehensive design from theory into something people could act on with their hands.' },
    ],
  },
  {
    id: 'dubois',
    name: 'W.E.B. Du Bois',
    initials: 'WD',
    era: '1868–1963',
    field: 'Sociology and civil rights',
    gravityProfile: {
      mission: 'Use the tools of social science — data, history, and narrative — to dismantle the structures that make racial inequality seem natural and inevitable.',
      desiredReputation: 'The scholar-activist who proved that racism is constructed, not innate',
      thinkingPartner: 'Someone who holds both rigorous empirical analysis and moral urgency at the same time — who knows that data alone never changed a mind, but neither did outrage alone.',
      story: 'I am the first African American to earn a doctorate from Harvard. I have written over twenty books. The work does not end.',
    },
    contacts: [
      { id: 'wd-1', name: 'Ida B. Wells', role: 'Journalist and activist', status: 'CONVERSATION', why: 'Her investigative journalism — building the statistical case for lynching as a system rather than a series of incidents — gave Du Bois the empirical model for how social science could expose racial terror without relying on the willingness of witnesses to testify.' },
      { id: 'wd-2', name: 'Booker T. Washington', role: 'Educator and leader', status: 'IDENTIFIED', why: 'His insistence on economic self-sufficiency as the path to Black advancement forced Du Bois to develop the sharpest version of his own counter-argument — the disagreement without which the concept of the Talented Tenth would have remained unpressured.' },
      { id: 'wd-3', name: 'Franz Boas', role: 'Anthropologist', status: 'REPLIED', why: 'His anthropological proof that race was a cultural construction rather than a biological fact gave Du Bois the scientific foundation that sociology alone could not supply — the critical interdisciplinary bridge between science and the fight against racism.' },
      { id: 'wd-4', name: 'Langston Hughes', role: 'Poet and writer', status: 'REPLIED', why: 'His poetry demonstrated that the Harlem Renaissance was making an argument, not just producing art — that Black cultural production was evidence against the same claim that racism used to naturalize hierarchy.' },
      { id: 'wd-5', name: 'Paul Robeson', role: 'Actor and activist', status: 'CONVERSATION', why: 'His insistence that Black American struggle was inseparable from global anti-colonialism gave Du Bois\'s analysis its widest frame — the voice that refused to let the domestic fight be treated as separate from the international one.' },
    ],
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    initials: 'AT',
    era: '1912–1954',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'Define the boundary between what is mechanically computable and what is not — and build the machines that live at that boundary.',
      desiredReputation: 'The mathematician who gave machines the capacity to think',
      thinkingPartner: 'Someone who can think in formal systems without losing sight of the philosophical stakes — who knows that "can machines think" is not just an engineering problem.',
      story: 'I designed the mathematical foundations of computation before there were computers. Then I built them. The question I keep returning to is not whether machines can compute — they can — but whether there is something computation cannot reach.',
    },
    contacts: [
      { id: 'at-1', name: 'John von Neumann', role: 'Mathematician and physicist', status: 'CONVERSATION', why: 'His stored-program architecture turned Turing\'s theoretical universal machine into a physical structure that could be built — the transition from mathematical proof to engineering specification that made computation real.' },
      { id: 'at-2', name: 'Alonzo Church', role: 'Logician and mathematician', status: 'REPLIED', why: 'His independent proof of uncomputability through lambda calculus arrived at the same boundary by a completely different path — the convergence that confirmed the Church-Turing thesis was describing something real about the structure of computation itself.' },
      { id: 'at-3', name: 'Claude Shannon', role: 'Mathematician', status: 'CONVERSATION', why: 'His information theory gave computation a formal language for talking about signal, noise, and the transmission of meaning — the missing vocabulary that Turing\'s machines needed to become a general theory of communication.' },
      { id: 'at-4', name: 'Max Newman', role: 'Mathematician, Bletchley Park', status: 'REACHED_OUT', why: 'His introduction of mathematical logic at Cambridge gave Turing\'s mind the exact problem it was built to answer — the teacher who handed Turing the question of decidability in precisely the form that produced the universal machine.' },
      { id: 'at-5', name: 'Ludwig Wittgenstein', role: 'Philosopher', status: 'IDENTIFIED', why: 'His philosophical challenges to the foundations of mathematics — particularly the question of what a proof actually proves — kept the problem of computation from being treated as settled when the philosophical stakes were still entirely open.' },
    ],
  },
  {
    id: 'goodall',
    name: 'Jane Goodall',
    initials: 'JG',
    era: '1934–',
    field: 'Primatology and conservation',
    gravityProfile: {
      mission: 'Prove through patient observation that chimpanzees — and by extension all animals — have complex inner lives, and use that proof to transform how humans treat the natural world.',
      desiredReputation: 'The scientist who changed what it means to be human by watching other animals',
      thinkingPartner: 'Someone who understands that rigorous science and moral commitment are not in tension — that the facts, honestly seen, lead you to action.',
      story: 'I had no formal degree when Louis Leakey sent me to Gombe. He believed lack of academic conditioning was an advantage. I spent years being dismissed. Then the chimpanzees taught me things the textbooks did not know.',
    },
    contacts: [
      { id: 'jg-1', name: 'Louis Leakey', role: 'Paleoanthropologist', status: 'CONVERSATION', why: 'His conviction that a careful observer unconditioned by academic orthodoxy could discover things trained scientists would miss sent Goodall to Gombe — the sponsor who understood that method and credential are not the same thing.' },
      { id: 'jg-2', name: 'Hugo van Lawick', role: 'Wildlife filmmaker', status: 'CONVERSATION', why: 'His wildlife cinematography gave the Gombe observations a visual record that scientific papers alone could never achieve — the documentarian who understood that seeing is a different kind of knowing than reading.' },
      { id: 'jg-3', name: 'Birutė Galdikas', role: 'Primatologist', status: 'REPLIED', why: 'Her orangutan research at Camp Leakey ran parallel to Goodall\'s chimpanzee work — building the comparative database across great apes that gave every individual conclusion its broader evolutionary context.' },
      { id: 'jg-4', name: 'Dian Fossey', role: 'Primatologist', status: 'REPLIED', why: 'Her gorilla research, and the violence that ended it, sharpened Goodall\'s understanding of what conservation requires beyond observation — the example that proved scientific commitment was not sufficient protection against the forces destroying habitat.' },
      { id: 'jg-5', name: 'Frans de Waal', role: 'Primatologist and ethologist', status: 'IDENTIFIED', why: 'His systematic scientific case for primate empathy and social cognition gave the academic community a framework for taking Goodall\'s field observations seriously — translating personal witness into peer-reviewed evidence.' },
    ],
  },
  {
    id: 'lovelace',
    name: 'Ada Lovelace',
    initials: 'AL',
    era: '1815–1852',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'See what the Analytical Engine can do that its inventor has not yet imagined — and write that vision down before the world is ready to understand it.',
      desiredReputation: 'The first to see that a calculating machine could operate on symbols beyond number',
      thinkingPartner: 'Someone who can match mathematical precision with imaginative reach — who does not mistake what a machine has done for what it can do.',
      story: 'My mother insisted on mathematics to suppress my father\'s poetic nature. It did not work as intended. I have come to believe that poetic science — imagination disciplined by rigor — is the only kind worth practicing.',
    },
    contacts: [
      { id: 'al-1', name: 'Charles Babbage', role: 'Mathematician and inventor', status: 'CONVERSATION', why: 'His Analytical Engine provided the only existing design for a general-purpose calculating machine — the architecture that Lovelace recognized could manipulate any symbol, not only number, and whose inventor had not yet seen this.' },
      { id: 'al-2', name: 'Mary Somerville', role: 'Mathematician and scientist', status: 'CONVERSATION', why: 'Her mathematical work and her introduction to Babbage gave Lovelace both a model and a door — proof that mathematical analysis was available to women, and the social connection through which the actual work became possible.' },
      { id: 'al-3', name: 'Michael Faraday', role: 'Experimental physicist', status: 'REACHED_OUT', why: 'His practice of translating physical intuition into communicable form — making invisible forces describable to a general audience — gave Lovelace a working model for her own project of articulating what a machine could do that no one had yet put into words.' },
      { id: 'al-4', name: 'Augustus De Morgan', role: 'Mathematician and logician', status: 'REPLIED', why: 'His correspondence-based teaching of advanced mathematics gave Lovelace the formal rigor her notes on the Analytical Engine required — the logician who understood that symbolic reasoning was the same operation whether its subject was number or machine instruction.' },
      { id: 'al-5', name: 'William King-Noel', role: 'Earl of Lovelace', status: 'IDENTIFIED', why: 'His practical support for Lovelace\'s scientific correspondence and publication — at a time when such work by women required a husband\'s active permission — created the conditions under which the notes on the Analytical Engine could be completed at all.' },
    ],
  },
  {
    id: 'carson',
    name: 'Rachel Carson',
    initials: 'RC',
    era: '1907–1964',
    field: 'Marine biology and ecology',
    gravityProfile: {
      mission: 'Make the invisible world of ecological interconnection visible enough that ordinary people will fight to protect it — starting with the sea, ending with the land.',
      desiredReputation: 'The scientist who started the modern environmental movement by making facts beautiful',
      thinkingPartner: 'Someone who understands that scientific literacy requires more than data — it requires prose that carries the reader into the world the data describes.',
      story: 'I wrote Silent Spring knowing it would be attacked by the chemical industry with everything they had. I published it anyway. I had cancer by then and no time for caution.',
    },
    contacts: [
      { id: 'rc-1', name: 'Dorothy Freeman', role: 'Naturalist and correspondent', status: 'CONVERSATION', why: 'Her sustained correspondence — decades of letters that became Carson\'s most honest editorial relationship — shaped the prose of every book written for public audiences, the reader who told the truth about what worked and what didn\'t.' },
      { id: 'rc-2', name: 'E.B. White', role: 'Author and essayist', status: 'REPLIED', why: 'His essays in The New Yorker proved that precise scientific observation could be written with the kind of beauty that made readers lean toward the subject rather than away from it — the standard Carson was working toward in everything she published.' },
      { id: 'rc-3', name: 'Barry Commoner', role: 'Biologist and activist', status: 'REPLIED', why: 'His ecological laws — particularly the principle that everything connects to everything else — gave the specific findings of Silent Spring their theoretical underpinning, turning a documented case into a scientific framework.' },
      { id: 'rc-4', name: 'Marjorie Spock', role: 'Organic farming advocate', status: 'REACHED_OUT', why: 'Her early legal challenge to DDT spraying in Nassau County connected Carson to the first case where scientific findings about pesticides were being tested in court — the bridge between laboratory evidence and legal standing.' },
      { id: 'rc-5', name: 'Paul Brooks', role: 'Editor, Houghton Mifflin', status: 'CONVERSATION', why: 'His editorial support at Houghton Mifflin — including the decision to publish despite the certainty of chemical industry attack — was the institutional backing that gave Carson\'s argument the form it needed to reach the audience it did.' },
    ],
  },
  {
    id: 'wells',
    name: 'H.G. Wells',
    initials: 'HW',
    era: '1866–1946',
    field: 'Science fiction and futurism',
    gravityProfile: {
      mission: 'Use fiction as a laboratory for ideas that science and politics cannot yet address directly — to think ten, fifty, a hundred years forward and leave the map behind.',
      desiredReputation: 'The writer who made the future a place you could see',
      thinkingPartner: 'Someone who understands that imagination constrained by current conditions is not imagination — that the value of the speculative is precisely that it escapes the probable.',
      story: 'I grew up in a draper\'s shop and escaped through scholarship. I have written scientific romances, utopias, dystopias, history, and political theory. None of it is fiction exactly. All of it is an argument about what is possible.',
    },
    contacts: [
      { id: 'hw-1', name: 'T.H. Huxley', role: 'Biologist and educator', status: 'CONVERSATION', why: 'His teaching at the Normal School of Science gave Wells the rigorous biological foundation that distinguished scientific romance from mere fantasy — the educator who made the speculation disciplined enough to carry an argument.' },
      { id: 'hw-2', name: 'George Bernard Shaw', role: 'Playwright and social critic', status: 'REPLIED', why: 'His satirical method provided the most productive resistance to Wells\'s utopian thinking — the friend who attacked every position Wells held, forcing each idea to survive serious opposition before it reached the page.' },
      { id: 'hw-3', name: 'Bertrand Russell', role: 'Philosopher and mathematician', status: 'REPLIED', why: 'His conviction that rational analysis, applied consistently to human institutions, pointed toward a more intelligent social order gave Wells\'s political thinking its philosophical scaffolding.' },
      { id: 'hw-4', name: 'Arnold Bennett', role: 'Novelist', status: 'REACHED_OUT', why: 'His belief that fiction\'s job was to render the present faithfully rather than imagine the future provided the disagreement that kept Wells\'s own purpose sharply defined — the contrasting literary method that clarified what the speculative novel was actually for.' },
      { id: 'hw-5', name: 'Winston Churchill', role: 'Politician and writer', status: 'IDENTIFIED', why: 'His reading of Wells\'s pre-war predictions about aerial bombardment and tank warfare — and his failure to act on them until the events arrived — made him the standing proof that imagination can reach a place years before institutions are willing to go.' },
    ],
  },
  {
    id: 'arendt',
    name: 'Hannah Arendt',
    initials: 'HA',
    era: '1906–1975',
    field: 'Political philosophy',
    gravityProfile: {
      mission: 'Understand how totalitarianism became possible — and in understanding it, identify what political action and public life must protect against it ever happening again.',
      desiredReputation: 'The thinker who refused to let atrocity become incomprehensible',
      thinkingPartner: 'Someone who can think without a banister — who does not need established tradition or ideology to hold their thinking up — who is willing to follow an argument wherever it goes.',
      story: 'I fled Germany in 1933 and was stateless for 18 years. I reported on the Eichmann trial and wrote that evil could be ordinary — banal — and the attacks have not stopped since. I stand by the analysis. Discomfort is not a rebuttal.',
    },
    contacts: [
      { id: 'ha-1', name: 'Karl Jaspers', role: 'Philosopher', status: 'CONVERSATION', why: 'His philosophical commitment to the examined life — and his insistence that thinking was a public obligation, not a private luxury — gave Arendt the intellectual framework for treating political events as occasions for philosophy rather than occasions for abstraction.' },
      { id: 'ha-2', name: 'Mary McCarthy', role: 'Author and critic', status: 'CONVERSATION', why: 'Her friendship and unsparing editorial eye gave Arendt the most honest feedback available to her in America — the reader who would say when the argument collapsed rather than when it was merely unexpected.' },
      { id: 'ha-3', name: 'Walter Benjamin', role: 'Philosopher and critic', status: 'REPLIED', why: 'His analysis of historical catastrophe — the idea that the past contains compressed moments of crisis that the present must learn to read — ran alongside Arendt\'s own thinking on totalitarianism in ways that reinforced and deepened both.' },
      { id: 'ha-4', name: 'Heinrich Blücher', role: 'Philosopher and teacher', status: 'CONVERSATION', why: 'His sustained philosophical dialogue across decades of shared exile was the only intellectual relationship that changed Arendt\'s thinking in real time rather than confirming it — the mind that argued back and was right often enough to matter.' },
      { id: 'ha-5', name: 'Gershom Scholem', role: 'Scholar of Jewish mysticism', status: 'IDENTIFIED', why: 'His accusation that Arendt\'s analysis of Eichmann lacked love for the Jewish people forced her to articulate precisely what kind of obligation a political philosopher does and does not owe to the communities they study — the challenge that produced her most careful self-defense.' },
    ],
  },
]
