export const DEMO_ORBITS = [
  {
    id: 'faraday',
    name: 'Michael Faraday',
    initials: 'MF',
    era: '1791–1867',
    field: 'Electromagnetic science',
    gravityProfile: {
      mission: 'Translate invisible natural forces — electricity, magnetism, light — into visible phenomena that anyone can understand and verify. Prove that nature is unified, not fragmented.',
      desiredReputation: 'The experimenter who proved the unity of physical forces',
      thinkingPartner: 'Someone who can take intuitive physical observations and formalize them mathematically — to build what I can sense but cannot fully articulate.',
      story: 'Born the son of a blacksmith, self-taught from books in a bookbinder\'s shop. I found my way to the Royal Institution through sheer obsession with how the world actually works. I want thinking partners who care more about what\'s true than what\'s already known.',
    },
    contacts: [
      { id: 'mf-1', name: 'James Clerk Maxwell', role: 'Mathematician and physicist', status: 'CONVERSATION', why: 'Mathematician and physicist developing the formal language of electromagnetic fields. Faraday can feel the field lines but cannot write them mathematically — Maxwell might be the person who makes them permanent.' },
      { id: 'mf-2', name: 'Humphry Davy', role: 'Chemist and Royal Institution director', status: 'CONVERSATION', why: 'Chemist and director of the Royal Institution. The person who decides who gets access to the laboratory. Worth understanding what he sees in people before they\'ve proven anything.' },
      { id: 'mf-3', name: 'William Whewell', role: 'Philosopher of science', status: 'IDENTIFIED', why: 'Philosopher of science and prolific coiner of scientific terminology. Working on the question of how new phenomena get named — and whether the name shapes what gets discovered next.' },
      { id: 'mf-4', name: 'Charles Babbage', role: 'Mathematician and inventor', status: 'REPLIED', why: 'Mathematician and inventor attempting to make logical operations mechanical. Interesting overlap: both trying to find the rules hiding inside processes that look like they have none.' },
      { id: 'mf-5', name: 'John Tyndall', role: 'Physicist and science communicator', status: 'REPLIED', why: 'Physicist and science communicator at the Royal Institution. Thinking seriously about how scientific ideas reach people who weren\'t in the room when they were discovered.' },
    ],
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    initials: 'NT',
    era: '1856–1943',
    field: 'Electrical engineering',
    gravityProfile: {
      mission: 'Harness alternating current to deliver unlimited electrical power to every human on earth — and eventually transmit energy through the earth itself without wires.',
      desiredReputation: 'The inventor who rewired civilization',
      thinkingPartner: 'Someone who thinks in systems and understands that the dominant technology is rarely the best one — just the one that found money first.',
      story: 'I can visualize complete machines running in my mind before a single component is built. I need people around me who can hold a vision that does not yet exist in the world and treat it as already real.',
    },
    contacts: [
      { id: 'nt-1', name: 'George Westinghouse', role: 'Industrialist and inventor', status: 'CONVERSATION', why: 'Industrialist and inventor with unusual tolerance for long-horizon bets. One of the few people in industry asking whether power transmission could be restructured entirely rather than just improved.' },
      { id: 'nt-2', name: 'Thomas Edison', role: 'Inventor and businessman', status: 'IDENTIFIED', why: 'Inventor and businessman who built the DC infrastructure Tesla is working against. Understanding how someone this successful thinks about ownership and scale might matter more than the disagreement.' },
      { id: 'nt-3', name: 'Mark Twain', role: 'Writer and satirist', status: 'REPLIED', why: 'Writer and satirist with genuine curiosity about science and invention. One of the rare literary minds who spends real time in laboratories — interested in what technology means, not just what it does.' },
      { id: 'nt-4', name: 'Swami Vivekananda', role: 'Philosopher and Hindu monk', status: 'REPLIED', why: 'Philosopher and teacher working on Vedantic concepts of energy and matter as unified substance. The overlap with field theory is unexpected enough to be worth exploring.' },
      { id: 'nt-5', name: 'Ernst Mach', role: 'Physicist and philosopher of science', status: 'IDENTIFIED', why: 'Physicist and philosopher questioning the fundamental assumptions of Newtonian mechanics. If the framework everyone else is working inside is wrong, Mach is one of the few people asking that question seriously.' },
    ],
  },
  {
    id: 'fuller',
    name: 'Buckminster Fuller',
    initials: 'BF',
    era: '1895–1983',
    field: 'Design science',
    gravityProfile: {
      mission: 'Design comprehensive systems that allow all of humanity to live well on Earth\'s finite resources — starting with shelter, and ending nowhere.',
      desiredReputation: 'The comprehensive anticipatory design scientist',
      thinkingPartner: 'Someone who can hold the whole system simultaneously — economics, physics, ecology, and the human — without collapsing into any one discipline.',
      story: 'I was expelled from Harvard twice and considered suicide at 32. What stopped me was the question: what can one individual do that large institutions cannot? I\'ve spent the rest of my life finding out.',
    },
    contacts: [
      { id: 'bf-1', name: 'Isamu Noguchi', role: 'Sculptor and designer', status: 'CONVERSATION', why: 'Sculptor and designer moving between art and industrial design without treating them as separate. Working on whether form can carry structural logic without announcing it.' },
      { id: 'bf-2', name: 'Marshall McLuhan', role: 'Media theorist', status: 'REPLIED', why: 'Media theorist arguing that the medium reshapes perception regardless of content. If Fuller is right that geometry is an environment, McLuhan might have the vocabulary to explain why.' },
      { id: 'bf-3', name: 'John Cage', role: 'Composer and artist', status: 'REPLIED', why: 'Composer and artist experimenting with structure as a generative constraint rather than a limitation. His work at Black Mountain College is worth paying attention to.' },
      { id: 'bf-4', name: 'Edwin Land', role: 'Inventor and Polaroid founder', status: 'REACHED_OUT', why: 'Inventor and Polaroid founder obsessed with making complex science disappear into instant usability. Asking the same design question Fuller is asking — what does it look like when the technology gets out of the way.' },
      { id: 'bf-5', name: 'Jonas Salk', role: 'Virologist', status: 'REPLIED', why: 'Virologist who declined to patent the polio vaccine. Working from the assumption that the goal is distribution rather than ownership — a rare position in midcentury American science.' },
    ],
  },
  {
    id: 'dubois',
    name: 'W.E.B. Du Bois',
    initials: 'WD',
    era: '1868–1963',
    field: 'Sociology and civil rights',
    gravityProfile: {
      mission: 'Use the tools of social science — data, history, and narrative — to dismantle the structures that make racial inequality seem natural and inevitable.',
      desiredReputation: 'The scholar-activist who proved that racism is constructed, not innate',
      thinkingPartner: 'Someone who holds both rigorous empirical analysis and moral urgency at the same time — who knows that data alone never changed a mind, but neither did outrage alone.',
      story: 'I am the first African American to earn a doctorate from Harvard. I have written over twenty books. The work does not end.',
    },
    contacts: [
      { id: 'wd-1', name: 'Ida B. Wells', role: 'Journalist and activist', status: 'CONVERSATION', why: 'Journalist and investigator using documentation as political argument. Working on whether evidence, precisely gathered and publicly presented, can do what rhetoric alone cannot.' },
      { id: 'wd-2', name: 'Booker T. Washington', role: 'Educator and leader', status: 'IDENTIFIED', why: 'Educator and institution builder arguing for a completely different theory of progress. The disagreement is sharp enough that understanding his position might clarify what Du Bois\'s position actually is.' },
      { id: 'wd-3', name: 'Jane Addams', role: 'Social reformer and Hull House founder', status: 'REPLIED', why: 'Social reformer and Hull House founder asking how reform becomes structural rather than charitable. Building institutions rather than arguments — a different theory of change worth understanding.' },
      { id: 'wd-4', name: 'Langston Hughes', role: 'Poet and writer', status: 'REPLIED', why: 'Poet and writer at the center of the Harlem Renaissance. Working on whether art can carry political weight without becoming propaganda — a question Du Bois has been circling for years.' },
      { id: 'wd-5', name: 'Paul Robeson', role: 'Actor, singer, and activist', status: 'CONVERSATION', why: 'Actor, singer, and activist whose international platform is being systematically dismantled by the US government. Watching how he responds to that pressure might matter.' },
    ],
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    initials: 'AT',
    era: '1912–1954',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'Define the boundary between what is mechanically computable and what is not — and build the machines that live at that boundary.',
      desiredReputation: 'The mathematician who gave machines the capacity to think',
      thinkingPartner: 'Someone who can think in formal systems without losing sight of the philosophical stakes — who knows that "can machines think" is not just an engineering problem.',
      story: 'I designed the mathematical foundations of computation before there were computers. Then I built them. The question I keep returning to is not whether machines can compute — they can — but whether there is something computation cannot reach.',
    },
    contacts: [
      { id: 'at-1', name: 'Alonzo Church', role: 'Mathematician and logician', status: 'REPLIED', why: 'Mathematician working on computability from a purely logical direction using lambda calculus. Arrived at something very close to Turing\'s result independently — worth understanding where the approaches converge and where they don\'t.' },
      { id: 'at-2', name: 'John von Neumann', role: 'Mathematician and physicist', status: 'CONVERSATION', why: 'Mathematician and physicist translating theoretical computation into physical architecture. Working on what it actually takes to build a machine that can run any program — the gap between Turing\'s theory and something you can touch.' },
      { id: 'at-3', name: 'Claude Shannon', role: 'Mathematician and electrical engineer', status: 'CONVERSATION', why: 'Mathematician and electrical engineer trying to quantify information itself. If thinking is information processing, Shannon might be building the measurement system that makes the question answerable.' },
      { id: 'at-4', name: 'Dilly Knox', role: 'Cryptanalyst and Bletchley Park veteran', status: 'REPLIED', why: 'Cryptanalyst with decades of experience breaking systems that weren\'t supposed to be breakable. One of the few people at Bletchley who had already internalized that every cipher has a structure waiting to be found.' },
      { id: 'at-5', name: 'Max Newman', role: 'Mathematician', status: 'REACHED_OUT', why: 'Mathematician who taught Turing at Cambridge and is now running the computing group at Bletchley. Has been tracking this work longer than almost anyone — worth understanding what he thinks is still unsolved.' },
    ],
  },
  {
    id: 'goodall',
    name: 'Jane Goodall',
    initials: 'JG',
    era: '1934–',
    field: 'Primatology and conservation',
    gravityProfile: {
      mission: 'Prove through patient observation that chimpanzees — and by extension all animals — have complex inner lives, and use that proof to transform how humans treat the natural world.',
      desiredReputation: 'The scientist who changed what it means to be human by watching other animals',
      thinkingPartner: 'Someone who understands that rigorous science and moral commitment are not in tension — that the facts, honestly seen, lead you to action.',
      story: 'I had no formal degree when Louis Leakey sent me to Gombe. He believed lack of academic conditioning was an advantage. I spent years being dismissed. Then the chimpanzees taught me things the textbooks did not know.',
    },
    contacts: [
      { id: 'jg-1', name: 'Louis Leakey', role: 'Paleoanthropologist', status: 'CONVERSATION', why: 'Paleoanthropologist convinced that understanding human origins requires studying our closest living relatives. Willing to send researchers to the field without conventional credentials if he believes in the question they\'re asking.' },
      { id: 'jg-2', name: 'Hugo van Lawick', role: 'Wildlife photographer and filmmaker', status: 'CONVERSATION', why: 'Wildlife photographer and filmmaker working on how scientific observation gets translated into images people believe. The gap between what happens in the field and what reaches the public is not trivial.' },
      { id: 'jg-3', name: 'Dian Fossey', role: 'Primatologist', status: 'REPLIED', why: 'Primatologist in the field with mountain gorillas, asking a version of the same question Goodall is asking. What she\'s finding with a different species might complicate or confirm what\'s happening at Gombe.' },
      { id: 'jg-4', name: 'David Attenborough', role: 'Natural historian and broadcaster', status: 'REPLIED', why: 'Natural historian and broadcaster thinking seriously about how science reaches mass audiences without losing its accuracy. The question of who gets to care about the natural world depends partly on who gets to hear about it.' },
      { id: 'jg-5', name: 'Rachel Carson', role: 'Marine biologist and writer', status: 'IDENTIFIED', why: 'Marine biologist and writer whose work is reshaping how the public understands ecosystems. The political environment her writing is creating might determine whether conservation science gets funded or ignored.' },
    ],
  },
  {
    id: 'lovelace',
    name: 'Ada Lovelace',
    initials: 'AL',
    era: '1815–1852',
    field: 'Mathematics and computation',
    gravityProfile: {
      mission: 'See what the Analytical Engine can do that its inventor has not yet imagined — and write that vision down before the world is ready to understand it.',
      desiredReputation: 'The first to see that a calculating machine could operate on symbols beyond number',
      thinkingPartner: 'Someone who can match mathematical precision with imaginative reach — who does not mistake what a machine has done for what it can do.',
      story: 'My mother insisted on mathematics to suppress my father\'s poetic nature. It did not work as intended. I have come to believe that poetic science — imagination disciplined by rigor — is the only kind worth practicing.',
    },
    contacts: [
      { id: 'al-1', name: 'Charles Babbage', role: 'Mathematician and inventor', status: 'CONVERSATION', why: 'Mathematician and inventor designing the Analytical Engine — a machine that could theoretically execute any mathematical operation if given the right instructions. The question of what those instructions could do is still completely open.' },
      { id: 'al-2', name: 'Mary Somerville', role: 'Mathematician and scientist', status: 'CONVERSATION', why: 'Mathematician and scientist whose work spans disciplines in ways the Royal Society rarely tolerates. One of the few people who might take seriously the idea that a woman is doing original mathematical work.' },
      { id: 'al-3', name: 'Michael Faraday', role: 'Physicist', status: 'REACHED_OUT', why: 'Physicist trying to find the hidden rules governing electromagnetic phenomena. Working on a different substrate but asking a recognizably similar question — what are the laws underneath the appearance.' },
      { id: 'al-4', name: 'Augustus De Morgan', role: 'Mathematician and logician', status: 'REPLIED', why: 'Mathematician and logician working on the foundations of algebra and formal reasoning. Might have something to say about whether the Analytical Engine\'s operations are mathematical in the deepest sense.' },
      { id: 'al-5', name: 'William Frend', role: 'Mathematician and social reformer', status: 'IDENTIFIED', why: 'Mathematician and social reformer who was one of the first people to take Ada\'s interest in mathematics seriously before Babbage did. Worth understanding what he saw early that others missed.' },
    ],
  },
  {
    id: 'carson',
    name: 'Rachel Carson',
    initials: 'RC',
    era: '1907–1964',
    field: 'Marine biology and ecology',
    gravityProfile: {
      mission: 'Make the invisible world of ecological interconnection visible enough that ordinary people will fight to protect it — starting with the sea, ending with the land.',
      desiredReputation: 'The scientist who started the modern environmental movement by making facts beautiful',
      thinkingPartner: 'Someone who understands that scientific literacy requires more than data — it requires prose that carries the reader into the world the data describes.',
      story: 'I wrote Silent Spring knowing it would be attacked by the chemical industry with everything they had. I published it anyway. I had cancer by then and no time for caution.',
    },
    contacts: [
      { id: 'rc-1', name: 'Dorothy Freeman', role: 'Friend and correspondent', status: 'CONVERSATION', why: 'Friend and correspondent with no scientific background who reads Carson\'s drafts as a general reader. Her responses track exactly where the science starts losing the story — an editorial function that can\'t be replicated.' },
      { id: 'rc-2', name: 'E.B. White', role: 'Writer and essayist', status: 'REPLIED', why: 'Writer and essayist who understands that how an argument is written determines whether it gets heard. Paying attention to the same tension between precision and readability that Carson is navigating.' },
      { id: 'rc-3', name: 'Clarence Cottam', role: 'Wildlife biologist', status: 'CONVERSATION', why: 'Wildlife biologist with access to field data on pesticide effects that Carson needs to make the argument airtight. Working on the same problem from inside the scientific establishment.' },
      { id: 'rc-4', name: 'Justice William O. Douglas', role: 'Supreme Court Justice and conservationist', status: 'REPLIED', why: 'Supreme Court Justice and committed conservationist asking whether the legal system has the language to protect natural systems. The answer to that question might determine what Carson\'s book can actually change.' },
      { id: 'rc-5', name: 'Albert Schweitzer', role: 'Physician and philosopher', status: 'REACHED_OUT', why: 'Physician and philosopher whose reverence for life as an ethical framework is one of the few positions that puts human welfare and ecological health on the same side of the argument.' },
    ],
  },
  {
    id: 'ibwells',
    name: 'Ida B. Wells',
    initials: 'IB',
    era: '1862–1931',
    field: 'Investigative journalism and civil rights',
    gravityProfile: {
      mission: 'Document racial violence with enough precision that denial becomes impossible — and publish it regardless of the threats made against the person doing the documenting.',
      desiredReputation: 'The journalist who made racial terror undeniable',
      thinkingPartner: 'Someone who understands that truth documented is not the same as truth heard — who knows that reaching the institutions of power requires strategy as much as evidence.',
      story: 'Born into slavery six months before the Emancipation Proclamation. I owned a newspaper by twenty-five. When three of my friends were lynched in Memphis, I went to the site, gathered the evidence, and published the truth. A mob destroyed my press and warned me out of the city at gunpoint. I kept writing.',
    },
    contacts: [
      { id: 'iw-1', name: 'Frederick Douglass', role: 'Abolitionist and statesman', status: 'CONVERSATION', why: 'Abolitionist, statesman, and the most important Black public voice of the previous generation. Still active, still writing, still thinking about the gap between legal freedom and actual freedom.' },
      { id: 'iw-2', name: 'W.E.B. Du Bois', role: 'Sociologist and activist', status: 'REPLIED', why: 'Sociologist and writer trying to make the conditions of Black life in America undeniable through data and analysis. Working on the same problem Wells is working on — what kind of evidence forces a response.' },
      { id: 'iw-3', name: 'Jane Addams', role: 'Social reformer', status: 'REPLIED', why: 'Social reformer with access to political networks and institutional infrastructure that Wells doesn\'t have. Thinking about how reform becomes policy rather than just argument.' },
      { id: 'iw-4', name: 'Mary Church Terrell', role: 'Educator and activist', status: 'CONVERSATION', why: 'Educator and activist building organizational infrastructure for Black women\'s political participation. Working on the question of what institutions you build when the existing ones won\'t include you.' },
      { id: 'iw-5', name: 'T. Thomas Fortune', role: 'Journalist and newspaper editor', status: 'CONVERSATION', why: 'Journalist and newspaper editor who controls one of the most important Black press platforms in the country. The question of who owns the platform matters as much as what gets published on it.' },
    ],
  },
  {
    id: 'arendt',
    name: 'Hannah Arendt',
    initials: 'HA',
    era: '1906–1975',
    field: 'Political philosophy',
    gravityProfile: {
      mission: 'Understand how totalitarianism became possible — and in understanding it, identify what political action and public life must protect against it ever happening again.',
      desiredReputation: 'The thinker who refused to let atrocity become incomprehensible',
      thinkingPartner: 'Someone who can think without a banister — who does not need established tradition or ideology to hold their thinking up — who is willing to follow an argument wherever it goes.',
      story: 'I fled Germany in 1933 and was stateless for 18 years. I reported on the Eichmann trial and wrote that evil could be ordinary — banal — and the attacks have not stopped since. I stand by the analysis. Discomfort is not a rebuttal.',
    },
    contacts: [
      { id: 'ha-1', name: 'Mary McCarthy', role: 'Writer and critic', status: 'CONVERSATION', why: 'Writer and critic with a reputation for intellectual precision and genuine willingness to disagree in public. One of the few people in New York literary circles who might push back hard enough to be useful.' },
      { id: 'ha-2', name: 'Karl Jaspers', role: 'Philosopher', status: 'CONVERSATION', why: 'Philosopher maintaining correspondence across war and displacement. Still thinking seriously about guilt, responsibility, and what philosophy owes to political reality — questions Arendt is circling from a different direction.' },
      { id: 'ha-3', name: 'Walter Benjamin', role: 'Philosopher and critic', status: 'REPLIED', why: 'Philosopher and critic working on how historical catastrophe gets understood by the people living inside it. His situation — stateless, trying to escape — is not abstract to Arendt.' },
      { id: 'ha-4', name: 'Heinrich Blücher', role: 'Philosopher and poet', status: 'CONVERSATION', why: 'Philosopher and poet who thinks differently enough from Arendt to be genuinely generative. The person whose objections to an idea reveal whether the idea holds.' },
      { id: 'ha-5', name: 'Hans Jonas', role: 'Philosopher', status: 'REPLIED', why: 'Philosopher and former student of Heidegger who broke with him over Nazism. Working on the question of what ethical responsibility looks like when technology changes the scale of human consequences.' },
    ],
  },
]
